In [1]:
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
x = np.arange(1, 25).reshape(12, 2)
y = np.array([0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0])
x

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24]])

In [3]:
y

array([0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0])

In [4]:
x_train, x_test, y_train, y_test = train_test_split(x, y)

In [5]:
x_train

array([[15, 16],
       [ 1,  2],
       [19, 20],
       [ 9, 10],
       [ 7,  8],
       [11, 12],
       [ 5,  6],
       [21, 22],
       [23, 24]])

In [6]:
x_test

array([[13, 14],
       [ 3,  4],
       [17, 18]])

In [7]:
y_train

array([1, 0, 0, 1, 0, 0, 1, 1, 0])

In [8]:
y_test

array([0, 1, 1])

In [9]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=4, random_state=4)

In [10]:
x_train

array([[17, 18],
       [ 5,  6],
       [23, 24],
       [ 1,  2],
       [ 3,  4],
       [11, 12],
       [15, 16],
       [21, 22]])

In [11]:
x_test

array([[ 7,  8],
       [ 9, 10],
       [13, 14],
       [19, 20]])

In [12]:
y_train

array([1, 1, 0, 0, 1, 0, 1, 1])

In [13]:
y_test

array([0, 1, 0, 0])

In [17]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.5, random_state=4, stratify=y)

In [18]:
x_train

array([[21, 22],
       [17, 18],
       [13, 14],
       [15, 16],
       [19, 20],
       [23, 24]])

In [19]:
x_test

array([[ 5,  6],
       [ 7,  8],
       [ 1,  2],
       [ 3,  4],
       [ 9, 10],
       [11, 12]])

In [20]:
y_train

array([1, 1, 0, 1, 0, 0])

In [21]:
y_test

array([1, 0, 0, 1, 1, 0])

In [22]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, shuffle=False)

In [23]:
x_train

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

In [24]:
x_test

array([[17, 18],
       [19, 20],
       [21, 22],
       [23, 24]])

In [25]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [26]:
x = np.arange(20).reshape(-1, 1)
y = np.array([5, 12, 11, 19, 30, 29, 23, 40, 51, 54, 74, 62, 68, 73, 89, 84, 89, 101, 99, 106])
x

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [27]:
y

array([  5,  12,  11,  19,  30,  29,  23,  40,  51,  54,  74,  62,  68,
        73,  89,  84,  89, 101,  99, 106])

In [28]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=8, random_state=0)

In [29]:
model = LinearRegression()
model = model.fit(x_train, y_train)
model.intercept_

3.1617195496417523

In [30]:
model.coef_

array([5.53121801])

In [31]:
model.score(x_train, y_train)

0.9868175024574795

In [32]:
model.score(x_test, y_test)

0.9465896927715023

In [33]:
y_pred=model.predict(x_test)

In [34]:
y_pred

array([102.72364381,   8.69293756, 108.25486182,  47.41146366,
        58.47389969,  97.19242579,  36.34902764,  75.06755374])

In [ ]:
y_test

array([ 99,  12, 106,  51,  74, 101,  23,  73])

In [35]:
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
x, y = load_diabetes(return_X_y=True)
x

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [36]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [37]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [38]:
from sklearn.linear_model import LinearRegression
model = LinearRegression().fit(x_train, y_train)
model.score(x_train, y_train)

0.5539250081377072

In [39]:
model.score(x_test, y_test)

0.3322332173106184

In [40]:
y_pred = model.predict(x_test)

In [41]:
y_pred

array([238.46949509, 248.92812015, 164.05732579, 120.30774826,
       187.42483427, 259.04746969, 113.55788482, 188.07762807,
       149.49521726, 236.00758247, 172.24561893, 178.87936198,
       109.16034679,  92.13333574, 243.32766187,  87.35445583,
       155.72165684,  66.98992013, 100.42233598, 218.0957236 ,
       196.6646301 , 161.2972646 , 161.70870434, 156.52404017,
       197.88770177, 167.58280539, 120.7427979 ,  84.84033238,
       192.03438449, 160.60496231, 175.17348034,  84.22759674,
       145.80002729, 145.97264454, 140.96436257, 197.00423168,
       165.94319214, 190.6597389 , 128.22361933, 206.41497077,
        84.3575017 , 164.02262498, 144.10639773, 184.68996616,
       177.80076449,  74.33261184, 143.36644877, 138.68063137,
       120.80857573, 234.34288711, 161.94132344,  74.54325994,
       154.71683591, 156.78815442, 237.41798756, 174.23210042,
       190.87871793, 118.98140389, 132.20521501, 168.52914416,
       214.73950634, 171.42284128, 157.37648738, 108.86

In [42]:
y_test

array([321., 215., 127.,  64., 175., 275., 179., 232., 142.,  99., 252.,
       174., 129.,  74., 264.,  49.,  86.,  75., 101., 155., 170., 276.,
       110., 136.,  68., 128., 103.,  93., 191., 196., 217., 181., 168.,
       200., 219., 281., 151., 257.,  49., 198.,  96., 179.,  95., 198.,
       244.,  89., 214., 182.,  84., 270., 156., 138., 113., 131., 195.,
       171., 122.,  61., 230., 235.,  52., 121., 144., 107., 132., 302.,
        53., 317., 137.,  57.,  98., 170.,  88.,  90.,  67., 163., 104.,
       186., 180., 283., 141., 150.,  47., 297., 104.,  49., 103., 142.,
        59.])

In [43]:
from sklearn.metrics import max_error
max_error(y_test,y_pred)

162.7395063416074

In [44]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.3322332173106184

In [45]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test,y_pred)

46.17358500370479

In [46]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test,y_pred)

3424.259334298692

In [47]:
from math import sqrt
sqrt(mean_squared_error(y_test,y_pred))

58.51717127731562

## Lab 17
1. WAP to perform Linear Regerssion on Diabetes Dataset and find the R sqaured score
2. WAP to perform Linear Regerssion on Diabetes Dataset and find the max error
3. WAP to perform Linear Regerssion on California Housing Dataset and find the RMSE, MAE and MSE