In [ ]:
import numpy as np
rng = np.random.RandomState(1)
X = rng.randint(5, size=(6, 100))
y = np.array([1, 2, 3, 4, 5, 6])
from sklearn.naive_bayes import CategoricalNB
clf = CategoricalNB()
clf.fit(X, y)
print(clf.predict(X[2:3]))

[3]


In [ ]:
import numpy as np
rng = np.random.RandomState(1)
X = rng.randint(5, size=(6, 100))
y = np.array([1, 2, 3, 4, 5, 6])
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
clf.fit(X, y)
print(clf.predict(X[2:3]))

[3]


In [ ]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
X, y = load_iris(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=0)
gnb = GaussianNB()
y_pred = gnb.fit(X_train, y_train).predict(X_test)
print("Number of mislabeled points out of a total %d points : %d"
      % (X_test.shape[0], (y_test != y_pred).sum()))

Number of mislabeled points out of a total 75 points : 4


In [ ]:
from sklearn.preprocessing import OrdinalEncoder
enc = OrdinalEncoder()
X = [['Male', 1], ['Female', 3], ['Female', 2]]
enc.fit(X)
enc.categories_
enc.transform([['Female', 3], ['Male', 1]])

array([[0., 2.],
       [1., 0.]])

In [1]:
import numpy as np
import pandas as pd

dataset = pd.read_csv('weather.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [2]:
from sklearn.preprocessing import OrdinalEncoder
enc = OrdinalEncoder()
enc.fit(X)
enc.categories_

[array(['Overcast', 'Rainy', 'Sunny'], dtype=object),
 array(['Cool', 'Hot', 'Mild'], dtype=object),
 array(['High', 'Normal'], dtype=object),
 array([False, True], dtype=object)]

In [3]:
enc.transform([['Overcast', 'Hot', 'Normal', False]])

array([[0., 1., 1., 0.]])

In [4]:
enc.transform([['Sunny', 'Mild', 'High', True]])

array([[2., 2., 0., 1.]])

In [5]:
X = enc.transform(X)
X

array([[0., 1., 0., 0.],
       [0., 1., 1., 0.],
       [0., 0., 1., 1.],
       [0., 2., 0., 1.],
       [1., 1., 0., 0.],
       [1., 2., 0., 0.],
       [1., 0., 1., 0.],
       [1., 1., 0., 1.],
       [1., 2., 1., 1.],
       [2., 2., 0., 0.],
       [2., 0., 1., 0.],
       [2., 2., 1., 0.],
       [2., 0., 1., 1.],
       [2., 2., 0., 1.]])

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [7]:
X_train

array([[0., 0., 1., 1.],
       [2., 2., 0., 1.],
       [2., 2., 0., 0.],
       [0., 1., 1., 0.],
       [1., 1., 0., 1.],
       [2., 0., 1., 0.],
       [0., 2., 0., 1.],
       [0., 1., 0., 0.],
       [1., 2., 0., 0.],
       [2., 0., 1., 1.]])

In [10]:
from sklearn.naive_bayes import CategoricalNB
classifier = CategoricalNB()
classifier.fit(X_train, y_train)
classifier.predict(enc.transform([['Rainy', 'Hot', 'Normal', False]]))

array(['Yes'], dtype='<U3')